### ISSUE TITLE
Add ability to export GeoTIFF objects as Geopackages?

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#49]
Inspiration from @mdsumner, https://gist.github.com/mdsumner/d1666d0d1ca57493ecd50fa44c8fe6b1

**Comment by mdsumner** [comment]
As much as I encourage the exploration, I don't think this is likely to be a good option.  The main thing is that GeoPackage only supports *image* data (i. e Greyscale/Byte in one band, or RGB/Byte in three bands) and I suspect you are looking at raster data more generally (?, also maybe my take on GPKG is out of date by now). 

GeoTIFF is a very good format, is there specific problems with it?   The images I've trawled from BOM in the past were PNG or JPEG and so required (trivial) georegistration by offset/scale, but GeoTIFF would be a very fine outcome there. 


Happy to explore the pain points here and figure out what's best!  

Generally if it's raster *data* (not a colour model) then bundling series into NetCDF is best, but otherwise a respectable series of GeoTIFFs is as good as it gets.  Neither is perfect, and it depends on what happens next unfortunately.

**Comment by adamhsparks** [comment]
Thanks for the feedback @mdsumner. It was a thought I had just before bed last night. I've used the vector capabilities in [_GSODR_](https://github.com/ropensci/GSODR) so thought perhaps this was something to look into.

Saved me some time by tagging you.

**Comment by adamhsparks** [comment]
I think I'll just leave this for another day. Not really necessary, we can write NetCDF if we really want, but most users should be able to do that themselves if they wish.

**Comment by mdsumner** [comment]
I hadn't gotten to trying the new features, but I want to - we will use this, either me or colleagues. Writing NetCDF itself is actually pretty painful if a user has never done it, raster does it but only single slices to variables IIRC. 

A templated .nc definition, or navigating writeRaster to ease export from bomrang is the kind of thing I can easily help with.

**Comment by adamhsparks** [comment]
Thanks @mdsumner, I'll open another issue specifically for NetCDF and we can take a look at providing that functionality.
